version: '3.1'

# See here for another versions https://hub.docker.com/_/postgres
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somethingAboutSecurity
      POSTGRES_DB: test-incode-group

  migration.db:
    image: postgres:15.2
    restart: always
    ports:
      - 5429:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somethingAboutSecurity
      POSTGRES_DB: migration-test-incode-group

  ci.db:
    image: postgres:15.2
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somethingAboutSecurity
      POSTGRES_DB: ci-test-incode-group
